#!/bin/sh
#
# Writes apps/ios/Config.xcconfig from the repository .env.
#
# The Swift app used to read its Supabase settings from
# `ProcessInfo.processInfo.environment`, which only ever holds anything when
# XCUITest launches the app and injects them. Tapping the icon produced an app
# with no backend at all — see docs/swift-migration.md. Expo did this job for
# the React Native app by inlining EXPO_PUBLIC_* into the JS bundle at build
# time; this script is the replacement for that step.
#
# Run it before `xcodegen generate`. Config.xcconfig is gitignored, exactly as
# .env is: the publishable key is public by design and ships in every client
# build, but the repository does not record which project it points at.
#
# Usage:  apps/ios/Scripts/write-config.sh
set -eu

root=$(cd "$(dirname "$0")/../../.." && pwd)
env_file="$root/.env"
out="$root/apps/ios/Config.xcconfig"

if [ ! -f "$env_file" ]; then
  echo "write-config.sh: no .env at $env_file — copy .env.example and fill it in." >&2
  exit 1
fi

# Read without sourcing: .env holds FDC_API_KEY, which is an Edge Function
# secret and has no business in this process, let alone in a build setting.
read_key() {
  sed -n "s/^[[:space:]]*\(export[[:space:]][[:space:]]*\)\{0,1\}$1=//p" "$env_file" \
    | tail -n 1 \
    | sed -e "s/^['\"]//" -e "s/['\"][[:space:]]*$//" -e 's/[[:space:]]*$//'
}

url=$(read_key EXPO_PUBLIC_SUPABASE_URL)
key=$(read_key EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY)

if [ -z "$url" ] || [ -z "$key" ]; then
  echo "write-config.sh: .env is missing EXPO_PUBLIC_SUPABASE_URL or EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY." >&2
  exit 1
fi

# An xcconfig treats `//` as the start of a comment, so `https://host` would be
# silently truncated to `https:`. The scheme and host are kept apart here and
# rejoined in project.yml, where the value is YAML and `//` means nothing.
scheme=${url%%://*}
host=${url#*://}
host=${host%/}

if [ "$scheme" = "$url" ] || [ -z "$host" ]; then
  echo "write-config.sh: EXPO_PUBLIC_SUPABASE_URL is not scheme://host." >&2
  exit 1
fi

cat > "$out" <<CONFIG
// Generated by apps/ios/Scripts/write-config.sh from the repository .env.
// Do not edit, and do not commit: this file is gitignored.
SUPABASE_URL_SCHEME = $scheme
SUPABASE_URL_HOST = $host
SUPABASE_PUBLISHABLE_KEY = $key
CONFIG

# Deliberately does not echo the host or the key. Neither is secret — both ship
# in every client build — but the repository records only the local alias for
# the Supabase project, and a build log is a poor place to start changing that.
echo "write-config.sh: wrote $out"
